version: '3'

services:
  vanna-app:
    build: .
    ports:
      - "8002:8002"  # app.py 的端口
      - "8501:8501"  # vanna-web.py 的端口（假設使用這個端口）
    volumes:
      - ./data:/data
    environment:
      - OLLAMA_HOST=http://ollama.mas4dev.xyz:11436
      - ./chromadb:/data/chromadb
    networks:
      - vanna-network

networks:
  vanna-network:
    driver: bridge 