version: '3.8'

services:
  vanna-api:
    build: .
    container_name: vanna-api
    ports:
      - "8002:8002"
      - "8084:8084"
    environment:
      - OLLAMA_HOST=http://10.10.10.168:11434
    volumes:
      - ./chromadb:/data/chromadb
    networks:
      - vanna-network
    restart: unless-stopped

networks:
  vanna-network:
    driver: bridge 